version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
  db:
    image: postgres:latest
    volumes:
      - volume1:/var/lib/postgresql/data
volumes:
  volume1:
    name: volume1
